# Cấu hình ứng dụng Address Parser
app:
  name: "Address Parser VN"
  version: "1.0.0"
  environment: "development"
  port: 8080
  debug: true

# Cấu hình hiệu năng
performance:
  # Worker pool configuration
  cpu_workers: 8
  io_workers: 32
  batch_size: 64
  max_qps_per_worker: 100
  
  # Cache configuration
  l1_cache_size: 10000
  cache_ttl_hours: 24
  
  # Processing thresholds
  min_confidence: 0.6
  confidence_high: 0.9
  top_k_candidates: 5

# Cấu hình Meilisearch
meilisearch:
  url: "http://meilisearch:7700"
  master_key: "5pAVWqmP046jvNzQwD70n8b5AdEyhW3lwWUZ1g5CZ8k"
  index_prefix: "address_"
  max_inflight: 100
  timeout_seconds: 30

# Cấu hình MongoDB
mongodb:
  url: "mongodb://mongodb:27017"
  database: "address_parser"
  collections:
    admin_units: "admin_units"
    address_cache: "address_cache"
    address_review: "address_review"
    learned_aliases: "learned_aliases"

# Cấu hình Redis
redis:
  host: "redis"
  port: 6379
  password: ""
  database: 0
  timeout: 5s
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  ttl: 3600 # 1 giờ
  key_prefix: "addr_parser:"

# Cấu hình logging
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "storage/logs/app.log"
  max_size_mb: 100
  max_age_days: 7

# Cấu hình monitoring
monitoring:
  prometheus_enabled: true
  prometheus_port: 9090
  tracing_enabled: true
  health_check_interval: 30

# Cấu hình Parser
parser:
  level_config: 4
  use_normalizer_v2: true
  use_libpostal: true
  jw_weight: 0.7
  lev_weight: 0.3
  scoring:
    weights:
      ward: 0.4
      district: 0.3
      province: 0.2
      structural_bonus: 0.1
      roadcode_bonus: 0.1
      poi_bonus: 0.1
      libpostal_coverage: 0.2
  thresholds:
    high: 0.8
    review_low: 0.6
  confidence:
    score_weight: 0.6
    completeness_weight: 0.3
    path_weight: 0.1
  meili:
    topk_ward: 5
    topk_district: 3
    topk_province: 2
